<a href="https://colab.research.google.com/github/Tmiller68/machine-learning-fundamentals/blob/main/Adult_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from re import X
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
column_names = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education_num",
    "marital_status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital_gain",
    "capital_loss",
    "hours_per_week",
    "native_country",
    "income"
]
df=pd.read_csv(
    "adult.data",
    names=column_names,
    header=None
    )
X=df.drop("income", axis=1)
y=df["income"]
X = pd.get_dummies(X, drop_first=True)
print(X.head())

   age  fnlwgt  education_num  capital_gain  capital_loss  hours_per_week  \
0   39   77516             13          2174             0              40
1   50   83311             13             0             0              13
2   38  215646              9             0             0              40
3   53  234721              7             0             0              40
4   28  338409             13             0             0              40

   workclass_ Federal-gov  workclass_ Local-gov  workclass_ Never-worked  \
0                   False                 False                    False
1                   False                 False                    False
2                   False                 False                    False
3                   False                 False                    False
4                   False                 False                    False

   workclass_ Private  ...  native_country_ Portugal  \
0               False  ...                     False
1               False  ...                     False
2                True  ...                     False
3                True  ...                     False
4                True  ...                     False

   native_country_ Puerto-Rico  native_country_ Scotland  \
0                        False                     False
1                        False                     False
2                        False                     False
3                        False                     False
4                        False                     False

   native_country_ South  native_country_ Taiwan  native_country_ Thailand  \
0                  False                   False                     False
1                  False                   False                     False
2                  False                   False                     False
3                  False                   False                     False
4                  False                   False                     False

   native_country_ Trinadad&Tobago  native_country_ United-States  \
0                            False                           True
1                            False                           True
2                            False                           True
3                            False                           True
4                            False                          False

   native_country_ Vietnam  native_country_ Yugoslavia
0                    False                       False
1                    False                       False
2                    False                       False
3                    False                       False
4                    False                       False

[5 rows x 100 columns]

In [5]:
from google.colab import files
uploaded = files.upload()

Saving adult.data to adult (1).data

In [6]:
print(df.columns)

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='object')

In [7]:
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [8]:
df.tail()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [9]:
df.shape

(32561, 15)

In [10]:
print(df.columns)

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='object')

In [11]:
y=y.str.strip()

In [12]:
x=df.drop("income", axis=1)
y=df["income"]

In [41]:
print(np.unique(y))

[0 1]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [14]:
df.duplicated().sum()

np.int64(24)

In [15]:
df.drop_duplicates()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [16]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [17]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [18]:
df.dropna()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [19]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income'],
      dtype='object')

In [20]:
df.duplicated().sum()

np.int64(24)

In [21]:
df['age']=df['age'].fillna(df['age'].mean())

In [22]:
df['age']=df['age'].fillna(df['age'].median())

In [23]:
df['workclass']=df['workclass'].fillna(df['workclass'].mode()[0])

In [24]:
df=df.ffill()

In [25]:
df=df.bfill()

In [26]:
df["age"]=df["age"].astype(int)

In [27]:
age=df["age"].to_numpy()
np.mean(age)

np.float64(38.58164675532078)

In [28]:
np.median(age)

np.float64(37.0)

In [29]:
np.min(age)

np.int64(17)

In [30]:
np.max(age)

np.int64(90)

In [31]:
hours=df["hours_per_week"].to_numpy()

In [32]:
np.mean(hours)

np.float64(40.437455852092995)

In [33]:
np.median(hours)

np.float64(40.0)

In [34]:
np.min(hours)

np.int64(1)

In [35]:
np.max(hours)

np.int64(99)

In [36]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
y=label_encoder.fit_transform(y)

In [37]:
print(label_encoder.classes_)

[' <=50K' ' >50K']

In [42]:
print(y[:10])

[0 0 0 0 0 0 0 1 1 1]

In [45]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [39]:
from sklearn.tree import DecisionTreeClassifier

unlimited_tree = DecisionTreeClassifier(
    random_state=42
)

unlimited_tree.fit(X_train, y_train)

NameError: name 'X_train' is not defined

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df["age"]=scaler.fit_transform(df[["age"]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df["age"]=scaler.fit_transform(df[["age"]])

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df["sex"]=encoder.fit_transform(df["sex"])

In [ ]:
plt.hist(df['age'], bins=15)
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.title('Age Distribution')
plt.show()

In [ ]:
income_counts = df['income'].value_counts()
plt.bar(income_counts.index, income_counts.values)
plt.xlabel("Income")
plt.ylabel("Number of People")
plt.title("Income Distribution")
plt.show()
#

In [ ]:
plt.hist(df['hours_per_week'], bins=20)
plt.xlabel('Hours per Week')
plt.ylabel('Frequency')
plt.title('Hours per Week Distribution')
plt.show()

In [ ]:
plt.scatter(df['age'], df['hours_per_week'])
plt.xlabel('Age')
plt.ylabel('Hours Worked Per Week')
plt.title('Age vs Hours Worked')
plt.show()

In [ ]:
plt.boxplot(df['age'])
plt.xlabel('Age')
plt.title('Age Distribution')
plt.show()

In [ ]:
correlation=df.corr(numeric_only=True)
print(correlation)

In [ ]:
plt.imshow(correlation)
plt.colorbar()
plt.xticks(range(len(correlation.columns)), correlation.columns, rotation=90)
plt.yticks(range(len(correlation.columns)), correlation.columns)
plt.title("Correlation Matrix")
plt.show()